version: '3.8'

services:
  rooms-api:
    build: 
      context: docker/dev
      dockerfile: Dockerfile
    volumes:
      - ./internal:/internal
    working_dir: /internal/rooms
    ports:
      - "9051:8080"
    env_file:
      .env
    networks:
      - hotelify-dev

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - hotelifydb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hotelify
      - POSTGRES_PASSWORD=hotelify
      - POSTGRES_DB=hotelify
    networks:
      - hotelify-dev

volumes:
  hotelifydb:

networks:
  hotelify-dev:

