openapi: '3.0.2'
info:
  title: Hotelify Rooms API
  version: '1.0'

servers:
  - url: http://{hostname}
    variables:
      hostname:
        default: localhost:9051

paths:
  /rooms/{uuid}:
    get:
      operationId: getRoom
      parameters:
        - in: path
          name: uuid
          schema: 
            type: string
          required: true
          description: Unique uuid of the room
      responses:
        '200':
          description: Room found and returned
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/room"
  /rooms:
    post:
      operationId: createRoom
      requestBody: 
        description: 'Room details'
        required: true

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postRoom'
      responses:
        '204':
          description: object will be created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
      room:
        type: object
        properties:
          uuid:
            type: string
          num: 
            type: string
          floor:
            type: integer
          services:
            type: array
            items:
              type: string
          beds:
            type: array
            items:
              type: object
              properties:
                bedType: 
                  type: string
                  enum: ['single-bed', 'sofa-bed', 'rollaway-bed', 'double-bed', 'queen-bed']
                count:
                  type: integer
      postRoom:
        type: object
        required: ['num', 'floor']
        properties:
          num: 
            type: string
          floor:
            type: integer
          services:
            type: array
            items:
              type: string
          beds:
            type: array
            items:
              type: object
              properties:
                bedType: 
                  type: string
                  enum: ['single-bed', 'sofa-bed', 'rollaway-bed', 'double-bed', 'queen-bed']
                count:
                  type: integer
      Error:
        type: object
        required:
          - slug
          - message
        properties:
          slug:
            type: string
          message:
            type: string

  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
