// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PostRoomBedsBedType.
const (
	PostRoomBedsBedTypeDoubleBed PostRoomBedsBedType = "double-bed"

	PostRoomBedsBedTypeQueenBed PostRoomBedsBedType = "queen-bed"

	PostRoomBedsBedTypeRollawayBed PostRoomBedsBedType = "rollaway-bed"

	PostRoomBedsBedTypeSingleBed PostRoomBedsBedType = "single-bed"

	PostRoomBedsBedTypeSofaBed PostRoomBedsBedType = "sofa-bed"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// PostRoom defines model for postRoom.
type PostRoom struct {
	Beds *[]struct {
		BedType *PostRoomBedsBedType `json:"bedType,omitempty"`
		Count   *int                 `json:"count,omitempty"`
	} `json:"beds,omitempty"`
	Floor    int       `json:"floor"`
	Num      string    `json:"num"`
	Services *[]string `json:"services,omitempty"`
}

// PostRoomBedsBedType defines model for PostRoom.Beds.BedType.
type PostRoomBedsBedType string

// CreateRoomJSONBody defines parameters for CreateRoom.
type CreateRoomJSONBody PostRoom

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody CreateRoomJSONBody
